---
title: "Q&A"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Process

## Budget Finanziario

- Le condizioni_commerciali di consuntivo e budget sono le stesse?

- Può esserci, in generale, una contabilizzazione >12 mesi?


### Meno importanti:

- Qual è il threshold per render certe aziende Top visibili o in Altri?

- (Cosa ci fa Good Truck lì visto che NON è Top Groupage?/ Perchè è scritto diverso?)

- In Trasporti qual è il threshold per dire che COOP ALLEANZA 3.0 SOC.COOP. la faccio vedere ma CENTRALE ADRIATICA SOC.COOP. che è sempre Top Trasporti no e la metto in Altri?


#### Answer

- Budget non si sposta.
Fatture a gennaio incasso a marzo, valore di gennaio a tot mesi successivi. Quando si fa budget dei primi mesi del 22 si va a vedere il consuntivo del 21.

- Le condizioni commerciali di norma sono le stesse fra budget e consuntivo

- Contabilizzazione è sempre <12 mesi


- Visibili sono i top fatturato

- (Good Truck no problem)

## Typos & Mismatches

### Input ...

- Attenzione valori condizioni commerciali, un punto di differenza: BON. BANC. VISTA. FATT. e BON. BANC. VISTA. FATT dopo risulta che condizioni commerciali adjusted hanno valori missing





# NUOVE----


- Budg finanziario, entrate correnti, Trasporto, per automatizzare il codice vanno divisi Centrale adriatica soc coop (1408) da 

Coop alleanza (1667)

- asimmetria tra mesi in input e gap mesi riportati in budget finanziario. questo è un problema per la coerenza dei risultati. 

- budget finanziario, perchè figure senza iva *1.22 piuttosto che i mesi ..._lordo_iva

- differenza tra "altri costi di funzionamento" e "altri costi diretti di funzionamento"

- Che cos'è totale importo di default? perchè c'entra con costi pubblicitari? Perchè solo a dicembre?